services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
      - ./master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    image: redis
    container_name: redis-slave1
    ports:
      - "6380:6379"
    volumes:
      - ./redis-slave1.conf:/usr/local/etc/redis/redis.conf
      - slave1-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master

  redis-slave2:
    image: redis
    container_name: redis-slave2
    ports:
      - "6381:6379"
    volumes:
      - ./redis-slave2.conf:/usr/local/etc/redis/redis.conf
      - slave2-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master

volumes:
  master-data:
  slave1-data:
  slave2-data: