services:
  redis:
    image: 'redis:latest'
    container_name: redis-3
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data: