services:
  redis-master:
    image: redis
    container_name: redis-master
    command: redis-server
      --requirepass 123456
      --masterauth 123456
      --slave-serve-stale-data yes
      --slave-read-only yes
      --repl-diskless-sync no
      --repl-diskless-sync-delay 5
      --repl-diskless-sync-delay 5
      --repl-disable-tcp-nodelay no
      --slave-priority 200
      --port 6379
    ports:
      - '6379:6379'
    sysctls:
      net.core.somaxconn: '511'

  redis-slave1:
    image: redis
    container_name: redis-slave1
    ports:
      - '6380:6379'
    command: redis-server
      --requirepass 123456
      --slave-serve-stale-data yes
      --slave-read-only yes
      --repl-diskless-sync no
      --repl-diskless-sync-delay 5
      --repl-diskless-sync-delay 5
      --repl-disable-tcp-nodelay no
      --slave-priority 150
      --slaveof redis-master 6379
      --masterauth 123456
      --port 6379
    sysctls:
      net.core.somaxconn: '511'

  redis-slave2:
    image: redis
    container_name: redis-slave2
    ports:
      - '6381:6379'
    command: redis-server
      --requirepass 123456
      --slave-serve-stale-data yes
      --slave-read-only yes
      --repl-diskless-sync no
      --repl-diskless-sync-delay 5
      --repl-diskless-sync-delay 5
      --repl-disable-tcp-nodelay no
      --slave-priority 100
      --slaveof redis-master 37370
      --masterauth 123456
      --port 6379
    sysctls:
      net.core.somaxconn: '511'

  sentinel1:
    image: redis
    container_name: redis-sentinel1
    ports:
      - '26379:26379'
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'

  sentinel2:
    image: redis
    container_name: redis-sentinel2
    ports:
      - '26380:26379'
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'

  sentinel3:
    image: redis
    container_name: redis-sentinel3
    ports:
      - '26381:26379'
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'